### ISSUE TITLE
Ds9 Time and resources

### ISSUE THREAD

**Issue by RoyalWolfie** [Powerthegreat/test#8]
We need to organize a time and place, and the Dvds
I have Ds9, But 1. its missing disks, and 2 its in storage, so eh!
Uh I'm happy to bike down like here and there to watch with, but we need jamies approval or something uwu

**Comment by P90ForRetail** [comment]
I can ask Jamie right now if it's okay. WIll let you know how it goes

**Comment by P90ForRetail** [comment]
He said yes. We have projector in the shed :)

**Comment by RoyalWolfie** [comment]
> 
> 
> He said yes. We have projector in the shed :)

Oh Cool

**Comment by RoyalWolfie** [comment]
We just need The Dvds
then

**Comment by Powerthegreat** [comment]
owo
